dependencies:
  LISParser:
    repo: dependencies/LISParser
    remotes:
      old_remote:
        url: git@github.com:NFDI-Matwerk-IUC02/demonstrator_notebooks.git
        sparse_checkout:
          path: Tools/lis2json
          branch: demonstrator_notebook
      origin: 
        url: git@github.com:NFDI-Matwerk-IUC02/LISParser.git




